export const NamesConstants = {
  GET_NAME_LIST_BY_CODE_SUCCESS: "GET_NAME_LIST_BY_CODE_SUCCESS",
  GET_NAME_LIST_BY_CODE_ERROR: "GET_NAME_LIST_BY_CODE_ERROR",
  CREATE_NAME_LIST_SUCCESS: "CREATE_NAME_LIST_SUCCESS",
  CREATE_NAME_LIST_ERROR: "CREATE_NAME_LIST_ERROR",
  GET_NAMES_BY_NAME_LIST_CODE_SUCCESS: "GET_NAMES_BY_NAME_LIST_CODE_SUCCESS",
  GET_NAMES_BY_NAME_LIST_CODE_ERROR: "GET_NAMES_BY_NAME_LIST_CODE_ERROR",
  CREATE_NAME_SUCCESS: "CREATE_NAME_SUCCESS",
  CREATE_NAME_ERROR: "CREATE_NAME_ERROR",
  CROSS_OUT_NAME_SUCCESS: "CROSS_OUT_NAME_SUCCESS",
  CROSS_OUT_NAME_ERROR: "CROSS_OUT_NAME_ERROR",
  NAME_RECEIVED_SUCCESS: "NAME_RECEIVED_SUCCESS"
};
